# -*- coding: utf-8 -*-
"""Cohort Analysis - Code Documentaion (bigquery)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/hybrid-sentry-479215-n9/locations/europe-west3/repositories/a6dd8b81-8ab0-41a7-a473-a609e13d4683

#🟦 **Cohort Analysis - Data Setup (bigquery)**

## 🔵1. **Data Ingestion: Local to Cloud Storage (GCS)**
"""

# 1. CSVs from Notebook → Cloud Storage

from google.cloud import storage

# Define your GCS bucket
bucket_name = "cohort_analysis_raw_data"

# Local files (already in Notebook root)
local_files = {
    "/ecom_orders.csv": "raw/ecom_orders.csv"
}

# Initialize GCS client
client = storage.Client()              # Connection to GCS
bucket = client.bucket(bucket_name)    # identifiy bucket_name

# Loop through all local → cloud file pairs
for local_path, gcs_path in local_files.items():

    # Create the Placeholder
    blob = bucket.blob(gcs_path)

    # Upload the local file into this blob (cloud file)
    blob.upload_from_filename(local_path)

    # Print confirmation: local → cloud
    print(f"Uploaded {local_path} → gs://{bucket_name}/{gcs_path}")

"""## 🔵 **2. Creating the Cohort Analysis Dataset (Schema)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA `hybrid-sentry-479215-n9.cohort_analysis`
# OPTIONS (
#     description = 'Dataset for Cohort_Analysis'
# );

"""## 🔵 **3. Defining and Creating the Target Table**"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# 
# CREATE OR REPLACE TABLE `hybrid-sentry-479215-n9.cohort_analysis.ecom_orders` (
# 
# row_id INT,
# customer_id STRING,
# order_date DATE,
# order_id STRING,
# sales FLOAT64
# 
# )
# 
# OPTIONS(description = "raw transactional data");

"""## 🔵 **3. Loading Data into the Destination Table (Load)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# 
# LOAD DATA INTO
#   `hybrid-sentry-479215-n9.cohort_analysis.ecom_orders`
# FROM FILES (
#   format = "CSV",
#   uris = ["gs://cohort_analysis_raw_data/raw/ecom_orders.csv"],
#   skip_leading_rows = 1,
#   field_delimiter = ","
# );

"""## 🔵 **Test Query**"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# 
# SELECT *
# FROM  `hybrid-sentry-479215-n9.cohort_analysis.ecom_orders`;